name: CI
on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    timeout-minutes: 10
    name: lint
    runs-on: "ubuntu-latest"
    permissions:
      contents: read # checkout
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@e06108dd0aef18192324c70427afc47652e63a82 # v7.5.0
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Run lints
        run: uv run ruff check . && uv run pyright && uv run mypy . && uv run python -c 'import giskard_hub'

  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.fork
    timeout-minutes: 10
    name: build
    runs-on: "ubuntu-latest"
    permissions:
      contents: read # checkout
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@e06108dd0aef18192324c70427afc47652e63a82 # v7.5.0
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Run build
        run: uv build

  test:
    timeout-minutes: 10
    name: test
    runs-on: "ubuntu-latest"
    permissions:
      contents: read # checkout
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@e06108dd0aef18192324c70427afc47652e63a82 # v7.5.0
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Run tests
        run: uv run pytest
